version: '3.8'

services:
  mysql-container:
    image: mysql:latest  # Use the name of the image you built
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script into the container
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
